version: "3.1"
services:
  api:
    build: ./src/api
    ports:
      - 7123:7123
    volumes:
      - ./resources:/resources:rw
      - ./resources/json:/resources/json:rw
      - ./resources/pptx:/resources/pptx:rw
      - ./resources/xlsx:/resources/xlsx:rw

  webapp:
    build: ./src/webapp
    container_name: webapp
    ports:
      - 5555:5555
    environment:
      - HTTPS=true
    volumes:
      - ./src/webapp:/usr/src/app
    working_dir: /usr/src/app
    
  caddy:
    image: caddy:2.8.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/caddy/:/etc/caddy/
    depends_on:
      - webapp

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - 8888:8888
    environment:
      - PORT=8888
      - SWAGGER_JSON=/openapi/openapi.json
      - BASE_URL=/api
    ## mount the swagger file to the environment
    volumes:
      - ./src/openapi:/openapi

  flask:
    build: ./src/flask
    ports:
      - 9456:9456
    volumes:
      - ./resources:/resources:rw
      - ./resources/json:/resources/json:rw
      - ./resources/pptx:/resources/pptx:rw
      - ./resources/xlsx:/resources/xlsx:rw

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo
    restart: always
    ports:
      - 6789:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_SITE_BASEURL: /mongo
